### ISSUE TITLE
Wrong balance and transaction history

### ISSUE THREAD

**Issue by mehrdd** [hybrix-io/hybrixd#31] opened 2020-11-16 20:35 UTC
Hello,
I created a sample `BTC` account in local Hybrixd,
and make 3 deposits in it and then checked in via console.

The system showed me some wrong balances and transaction history.

I send this amounts:
- 0.00005000
- 0.00003000
- 0.00003000

https://www.blockchain.com/btc/address/1LPwnPMX1MBoPbHqDDYpdEyUB6vVipBp6M

![hd](https://user-images.githubusercontent.com/1578360/99304731-fdd0e380-2867-11eb-8079-a7ddc22d6f26.png)

But as you can see every time i checked, it showed me some wrong numbers.
and after 10 minutes it showed the correct balance.
Why It showed me this numbers at first?
It seems very misleading to me...

**Comment by RoukePouw** [comment] 2020-11-24 13:45
Indeed, that's not good.  Thanks for notifying us!

It seems there was an overlap in the confirmed and unconfirmed balances.

Currently those are `{"confirmed":11000,"unconfirmed":0}`  again. 

But if an overlap would be summed and would therefor result in an erroneously high amount because of:

`math '${.confirmed}+${.unconfirmed}'  `

If these balances are not mutually exclusive we should refrain from using the sum of both these balances. I will update this in the bitcore engine.

**Comment by RoukePouw** [comment] 2020-12-08 13:49
This was fixed in 0.8.9. Thanks!

**Closed by RoukePouw** 2020-12-08 13:49 UTC
